---
version: '3.2'

services:
  empms-es:
    build:
      context: elasticsearch/
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: elastic
    networks:
      - ot-microservices

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://empms-es:9200"]'
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "elastic"
    depends_on:
      - empms-es
    networks:
      - ot-microservices

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.6
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.host=0.0.0.0:8200
        -E setup.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["empms-es:9200"]
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=elastic
    depends_on:
      - empms-es
    networks:
      - ot-microservices

  empms-db:
    build:
      context: mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "attendancedb"
    networks:
      - ot-microservices

  empms-attendance:
    build:
      context: attendance/
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./attendance/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
      ELASTIC_APM_SERVICE_NAME: "attendance"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
    networks:
      - ot-microservices
    depends_on:
      - empms-db

  empms-salary:
    build:
      context: salary/
    ports:
      - "8080:8080"
    environment:
      ELASTIC_APM_SERVICE_NAME: "salary"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      SPRING_ELASTICSEARCH_REST_URIS: "empms-es:9200"
      SPRING_ELASTICSEARCH_REST_USERNAME: elastic
      SPRING_ELASTICSEARCH_REST_PASSWORD: elastic
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-employee:
    build:
      context: employee/
    ports:
      - "8083:8083"
    volumes:
      - type: bind
        source: ./employee/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
      ELASTIC_APM_SERVICE_NAME: "employee"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-frontend:
    build:
      context: frontend/
    ports:
      - "5000:5000"
    networks:
      - ot-microservices

  empms-webserver:
    build:
      context: webserver/
    volumes:
      - type: bind
        source: ./webserver/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "80:80"
    networks:
      - ot-microservices
    depends_on:
      - empms-frontend

networks:
  ot-microservices:
    driver: bridge

volumes:
  elasticsearch:
